databases:
  - name: shared-racing-db  # Use one instance for both
    plan: free

services:
  - type: web
    name: flask-api-service
    env: docker
    dockerContext: ./flask_api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shared-racing-db
          property: connectionString
        # We will manually append /flask_db in the dashboard later

  - type: web
    name: django-racing-web
    env: docker
    dockerContext: ./django_web
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shared-racing-db
          property: connectionString
        # We will manually append /django_db in the dashboard later