databases:
  # 1. The Flask Database
  - name: flask-db-instance
    databaseName: flask_db
    user: postgres
    plan: free

  # 2. The Django Database
  - name: django-db-instance
    databaseName: django_db
    user: postgres
    plan: free

services:
  # 1. The Flask API
  - type: web
    name: flask-api-service
    env: docker
    plan: free
    dockerContext: ./flask_api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-db-instance
          property: connectionString

  # 2. The Django Web App
  - type: web
    name: django-racing-web
    env: docker
    plan: free
    dockerContext: ./django_web
    envVars:
      - key: FLASK_API_URL
        value: https://flask-api-service.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: django-db-instance
          property: connectionString
      - key: SECRET_KEY
        generateValue: true